// Note: Don't use these outside of the file, use APP_THEME instead
export const COLORS = {
  LIGHT_BLUE: "#A4D3FF",
  MEDIUM_BLUE: "#92C3F0",
  DARK_BLUE: "#258EEF",
  GREEN: "#90BC57",
  RED: "#F87272",
  LIGHT_GREY: "#F6F3F3",
  GREY: "#DCDCDC",
  WHITE: "#FFFFFF",
  BLACK: "#000000",
};

export const APP_THEME = {
  MODAL: COLORS.WHITE,
  BACKGROUND: COLORS.WHITE,
  TEXT_STANDARD: COLORS.BLACK,
  TEXT_SECONDARY: COLORS.GREY,
  TEXT_TERTIARY: COLORS.LIGHT_GREY,
  APP_BLUE: COLORS.LIGHT_BLUE,
  BLUE_MED: COLORS.MEDIUM_BLUE,
  BLUE_DARK: COLORS.DARK_BLUE,
  CONFIRM: COLORS.GREEN,
  CANCEL: COLORS.RED,
};

export const COLORS_DARK = {
  LIGHT_BLUE: "#1E6FBB", // Adjusted for dark mode
  MEDIUM_BLUE: "#92C3F0",
  DARK_BLUE: "#258EEF",
  GREEN: "#599806",
  RED: "#d70000",
  LIGHT_GREY: "#444444", // Darkened for dark mode
  GREY: "#A0A0A0",
  WHITE: "#FFFFFF",
  BLACK: "#000000",
  DARK_GREY: "#444444",
};
export const APP_THEME_DARK = {
  MODAL: COLORS_DARK.DARK_GREY,
  BACKGROUND: COLORS_DARK.BLACK,
  TEXT_STANDARD: COLORS_DARK.WHITE,
  TEXT_SECONDARY: COLORS_DARK.GREY,
  TEXT_TERTIARY: COLORS_DARK.LIGHT_GREY,
  APP_BLUE: COLORS_DARK.DARK_BLUE,
  BLUE_MED: COLORS_DARK.MEDIUM_BLUE,
  BLUE_DARK: COLORS_DARK.LIGHT_BLUE,
  CONFIRM: COLORS_DARK.GREEN,
  CANCEL: COLORS_DARK.RED,
};
